### ISSUE TITLE
1858 implementation meta-issue

### ISSUE THREAD

**Issue by ollybh** [ollybh/18xx#2]
# 1858 implementation notes and task list

## Rough implementation plan

- [x] Setup map, tiles and market
- [x] Game with public companies available from the start, no privates.
- [x] Track laying.
- [x] Tokening.
- [x] H/M/E/D trains.
- [x] Private auctions.
- [x] Exchanging privates for shares in public companies.
- [x] Track lays by privates.
- [x] Starting a public company from a private.
- [x] 5-share to 10-share conversions.
- [x] Private closure round.
- [x] Quick start variant.

### Operating round order

- [x] Privates owned by players pay revenue at the start of the operating round.
- [x] Privates lay track in numerical order, then public companies operate in stock market order.

### Operating round steps

- [x] Place track.
- [x] Place token.
- [x] Run trains.
- [x] Distribute earnings.
- [x] Close privates.
- [x] Buy trains.
- [x] Issue or redeem shares.

### Track laying.

- [x] Two track lays, either or both can be upgrades, second costs Pt20.
- [x] Only public companies can upgrade track.
- [x] Track laying costs (terrain or second tile) are halved for metre gauge track.
- [x] Semi-restrictive upgrades.
- [x] Routes for laying/upgrading track cannot include both metre and broad gauge track.
- [x] Yellow metre gauge track is only available after first 4H/2M train is bought.
- [x] Private companies do not pay terrain costs for their home hexes.
- [x] Private companies' first track lay must be in a home hex, unless there is already track there.
- [x] The private companies' home hexes are reserved, track can only be laid by the privates, or a public company that owns the private. If the hex is shared by two private companies then either can lay the track.
- [x] Some private companies have linked home hexes, track on these must be laid connecting them together.
- [x] Players must pay any costs for terrain or second track lays for private companies.
- [x] Players can pay the costs for terrain if a public company cannot afford it.
- [x] Players can pay the costs for second track lays if a public company cannot afford it. This is a variant, but the recommended way to play.

### Tokening

- [x] Routes for tokening cannot include both metre and broad gauge track.
- [x] Token costs are Pt40/provincial border crossed, or Pt20 if in the same province.
- [x] Public companies floated in phase 5 or later lay their home station when floated. It can be in any unoccupied city circle, and costs twice city's value (zero if the city has not yet been built).
- [x] Station spaces are reserved for private companies. A public company can ignore this restriction if it owns the private company.

### Trains

- [x] H trains count hex sides crossed.
- [x] E/M/D trains count large cities, off-board areas and ports visited.
- [x] E/D trains ignore small cities.
- [x] M trains count small cities. Their routes can start and end at small cities.
- [x] D trains double the value of the places visited.
- [x] H/E/D trains only run on broad or dual gauge track.
- [x] M trains only run on metre or dual gauge track.
- [x] Wounded trains halve the value of their runs.
- [x] Wounded trains can be discarded during the train buying step.
- [x] Wounded trains count against train limit.
- [x] Wounded trains can be bought across.
- [x] Discarded wounded trains are removed from play.
- [x] 6H/3M trains are rusted by the fifth grey train (7E/6M/5D) train purchased.

### Emergency money raising

- [x] A company is not obliged to own a train. It moves one space left on the stock market if it does not own a train at the end of its turn.
- [x] Can issue shares from the treasury, move one space left for this.
- [x] Director can contribute cash from hand.
- [x] Director cannot sell shares.
- [x] EMR can only be used to buy a train from the bank or the pool.
- [x] Don't have to buy the cheapest train.
- [x] EMR can be used to buy an expensive train even if a cheaper one could be bought without EMR.
- [x] EMR does not happen if not enough can be raised to afford a train.

### Distribute earnings

- [x] Privates owned by public companies pay their income as train revenue.
- [x] Public companies pay in full, half pay or withhold.
- [x] For odd earnings: divide revenue by five or ten, round down and pay that per share. The remainder gets paid to the company treasury.
- [x] Shares in the company treasury earn dividends, those in the bank pool do not.
- [x] Only move right if 10×dividend ≥ share price. No multiple jumps.
- [x] After revenue is paid, any privates owned by a public company close

## Stock rounds

- [x] On a turn you can do multiple sell actions, and then a single buy action.
- [x] Priority is the player to the left of the last person to take an action.
- [x] First stock round is the same as any other, except you cannot start a public company.
- [x] 60% limit on public company ownership.
- [x] 50% limit on shares in the pool.
- [x] Cannot sell director's certificate.
- [x] Stock price only drops for sales by the director, and is one space only.
- [x] Can start public companies directly after the start of phase 5. 20% to float.

### Sell actions

- [x] Sell shares.
- [x] Exchange a private company for a public company share. They must be connected. By consent only. Exchange for a share from the company treasury. Can place free token in private company's home, does not need to be connected to this hex.
- [x] Convert public company from 5-share to 10-share. Can be done in the same round that the company forms.

### Buy actions

- [x] Buy one public company share.
- [x] Start a public company.
- [x] Auction a private company.

### Private closure round

- [x] Occurs after the end of the operating round in which the first 5E/4M train is bought.
- [x] Privates closure in numerical order.
- [x] Each company is exchanged for a public company share, or sold to the bank for face value.
- [x] Must be connected to exchange for a share.
- [x] Need consent to be exchanged for a treasury share, do not need consent for a pool share.
- [x] If exchanged for a treasury share, the public company receives the private's face value to its treasury.
- [x] Can go over 60% ownership in this round, do not need to sell down.
- [x] Unsold private companies close.

### End of game

- [x] End of the operating round in which the bank breaks, or the end of the next operating round if it breaks during a stock round.
- [x] Does not end if the top of the stock market is reached.
- [x] Cannot go bankrupt.

## Map

- [x] Need to show private companies' home hexes.
- [x] Add port symbol to A16 and J1?
- [x] Check spelling of all place names.
