### ISSUE TITLE
18BF implementation meta-issue

### ISSUE THREAD

**Issue by ollybh** [ollybh/18xx#64]
# 18BF implementation notes and task list

Based on 18BF rules v.012.

## Game setup
- [ ] Starting capital £630/470/375.
- [ ] Map.
- [ ] Stock market.
- [ ] Private company definitions.
- [ ] Minor company definitions.
- [ ] Public company definitions.
- [ ] System definitions.
- [ ] Train definitions.
- [ ] Seven private railways in play, other three discarded.
- [ ] Minor company opening order.

### Phase 2
- [ ] Yellow track only.
- [ ] Train limit: 2 for minors.
- [ ] Certificate limit 32/24/19.

### Phase 3
- [ ] Green track available.
- [ ] Train limit: 2 for minors, 4 for majors.
- [ ] Can buy in privates.
- [ ] Merger rounds start.

### Phase 4
- [ ] 2Ts rust.
- [ ] Train limit: 1 for minors, 3 for majors.
- [ ] Public companies can be started by buying presidency.
- [ ] Export train at the end of OR set.

### Phase 5
- [ ] Brown track available.
- [ ] Train limit: 1 for minors, 3 for majors.
- [ ] Minor companies cannot be started.
- [ ] U1 available.

### Phase 6
- [ ] 3Ts rust.
- [ ] Train limit: 1 for minors, 2 for majors, 4 for systems.
- [ ] Systems can form.

### Phase 7
- [ ] Grey track available.
- [ ] Train limit: 1 for minors, 2 for majors, 4 for systems.
- [ ] U2 available.

### Phase 8
- [ ] 4Ts rust.
- [ ] Private railway companies close.
- [ ] Train limit: 0 for minors, 2 for majors, 4 for systems.
- [ ] 5+5E and 2+2 trains available.
- [ ] No more trains exported.
- [ ] Systems can double jump.
- [ ] Certificate limit 21/16/13.

## Stock rounds
- [ ] Must sell down if above certificate limit.
- [ ] On a turn you can sell shares, and then a buy a single share or start an auction.
- [ ] Ferries, undergrounds and minors are all auctioned.
- [ ] Pool limit is 50% of any company.
- [ ] 60% limit on major/system ownership.
- [ ] Cannot sell president's certificate.
- [ ] Share price moves left if the president sells shares, one space only.
- [ ] Can start public companies from phase 4, stock price £70–200. Home token goes to an unreserved and unconnected city (or just unreserved if nowhere is unconnected).
- [ ] Priority is the player to the left of the last person to take an action.
- [ ] No share price bump for fully sold.

### Initial stock round
- [ ] All seven private railway companies are auctioned in order.
- [ ] If everyone passes before anything has been bought then then switch to a Dutch auction.
- [ ] Minor auction after private railways have been bought.

### Operating round order
- [ ] Always two operating rounds in a set.
- [ ] Privates pay .
- [ ] Minors in stock price order.
- [ ] Majors in stock price order.
- [ ] Systems in stock price order.
- [ ] Train exported at the end of OR set (phases 4–7).

### Operating round steps
- [ ] Redeem shares.
- [ ] Lay/upgrade track.
- [ ] Place token.
- [ ] Run trains.
- [ ] Distribute earnings.
- [ ] Pay loan interest.
- [ ] Redeem loans.
- [ ] Buy trains.
- [ ] Buy private, £1 to face value, from phase 3.

### Track laying
- [ ] Two track lays, only one can be upgrade, most be different hexes, second costs £20.
- [ ] Systems get three track lays, still only one upgrade.
- [ ] Semi-restrictive upgrades.

### Tokening
- [ ] Token costs are £20 per hex from existing token.
- [ ] Cannot token a location if the company already has a token there (including all of London).

### Routes
- [ ] Towns may be skipped by all trains.
- [ ] Cities may be skipped by 5+5E.
- [ ] 2+2/3+3/4+4/5+5E double revenue.
- [ ] Cannot run to London unless the route ends at the company's token.
- [ ] Trains cannot run London–London.
- [ ] Trains cannot run Ireland–Ireland.
- [ ] Player must choose which of the Irish red areas to assign Irish Sea ferry bonuses to.
- [ ] If a company owns more than one Irish Sea ferry then the bonuses must go to different areas.
- [ ] Bonus for running London–red area.
- [ ] Bonuses for crossing national borders.
- [ ] G-trains do not have a route, score cities plus mine bonus.

### Dividends
- [ ] Minors always spit.
- [ ] Majors and systems may pay, split or withhold.
- [ ] Half-dividends are rounded up.
- [ ] System dividends are rounded down.
- [ ] Share price moves left on withhold or zero revenue.
- [ ] Share price moves right if dividend per share ≥ stock price.
- [ ] Systems double jump in phase 8 if dividend per share ≥ 2 × stock price.
- [ ] Company closes if share price moves into the 'closed' space.

### Loans
- [ ] Loans are worth £50.
- [ ] Receive £45 when taking out a loan.
- [ ] Loan limits are: minors 2, majors 5, systems 10.
- [ ] Interest is £5 per loan, not paid a second time when taking out a loan.
- [ ] Must take a loan (if possible) to pay interest if the company does not have enough money.
- [ ] If still cannot pay interest then empty treasury and move one space left on the stock market.
- [ ] Must redeem as many loans as possible.

### Emergency money raising
- [ ] If cannot afford a train then issue shares to buy one. No contribution from president.
- [ ] May take loans to buy a more expensive train, even if a cheaper one could be bought.
- [ ] If cannot afford a train after taking all possible loans then no loans are taken, and share price moves one space left.
- [ ] Systems may upgrade trains.
- [ ] If a train is returned to the bank pool then it does not change in type (5/3G, etc).

## Merger rounds
- [ ] Minors in stock price order, then majors in stock price order.

### Minor conversion
- [ ] Minors can convert if their share price is £100–165.
- [ ] President can buy up to 60% of new company, others can buy a single share.

### Minors merging
- [ ] Minors may merge if connected.
- [ ] 2–10 minors may merge (no more than 6 from a single player), one of them must be connected to all the others.
- [ ] Rickshaws in London only.
- [ ] Keep two station markers, not in the same city, apart from London.
- [ ] Can go over loan limit.
- [ ] All players owning the merging minors can buy up to 60% of new company, others can buy a single share.

### Minor takeover
- [ ] Minors can be taken over if they have a route to the major, are co-located in the same city, or both in London.
- [ ] Swapped for treasury share, can go over 60% this way and don't need to sell down.
- [ ] Can go over loan limit.
- [ ] Major can take station marker, or can decline. Can't have two stations in the same city, apart from London.

### System formation
- [ ] Two, three or four majors may merge to form a system. Must be connected and all directors must consent.
- [ ] Can go over loan limit.
- Two-way mergers:
  - [ ] 8 tokens.
  - [ ] New price is average of prices, rounded down to next available price.
  - [ ] Share are exchanged one-for-one.
- Three-way merger:
  - [ ] 12 tokens.
  - [ ] New price is sum of highest and lowest prices, rounded down and then moved four steps left.
  - [ ] Shares are exchanged three-for-two. Exchange triples where possible then (in player order, starting with the director) trade up to a full share by paying the difference to the treasury. Can only trade down and sell the partial share (receiving money from the bank). if the player cannot afford to trade up.
  - [ ] Discard tokens if there are more than 12 on the board. Can have tokens in the same city.
- Four-way merger:
  - [ ] 12 tokens.
  - [ ] New price is sum of highest and lowest prices, rounded down to the next available price.
  - [ ] Shares are exchanged two-for-one. Exchange triples where possible then (in player order, starting with the director) trade up to a full share by paying the difference to the treasury. Can only trade down and sell the partial share (receiving money from the bank). if the player cannot afford to trade up.
  - [ ] Discard tokens if there are more than 12 on the board. Can have tokens in the same city.

### End of game
- [ ] Triggered by the purchase of the first 4+4/6G train.
- [ ] If bought in first OR of set, finish current OR set, stock round, two more ORs.
- [ ] If bought in second OR of set, finish current OR, stock round, three more ORs.
- [ ] Stock price is moved left one step for each loan.
- [ ] Privates are worth face value.

**Comment by ollybh** [comment]
CC @ianwilson156/@Dave4B – this is a list of things that need to be done to get 18BF working on 18xx.games. Could you please check this for me?

@ianwilson156 one questions for you: What happens with minors in phase 8 in the train buying step? Move one space left as they can't own a train?

**Comment by Dave4B** [comment]
In phase 2, Privates with track laying powers may be used by any Minor company with the same director.

Majors which hit the Closed box may be restarted (unlikely but legal); Minors may not. Systems???

**Comment by ianwilson156** [comment]
Minors in phase 8: yes, they would move a space left (never seen it happen, minors tend to disappear before that).

In EMR, there is no issuing of shares. In fact, there is no issuing of shares at any time (just redeeming).

In a 3-way system formation, you cannot have more than 12 tokens, so the discard rule is irrelevant.

In a 4-way system formation, you trade doubles first (not triples).

Note: when trading up/down in system formation, always round normally (i.e 1/2 and 2/3 up, 1/3 down)

Note: private bonuses apply to all trains that run to that place i.e including G-trains.

Note: ferries are available once the 7 railway privates have been bought.

**Comment by ianwilson156** [comment]
Further note: after system formation, the majors involved are _not_ available to restart (like minors forming a major).

**Comment by ianwilson156** [comment]
Private track laying powers: can be used by any type of company in any phase, provided the owner/director of the company is the owner of the private. But the power _cannot_ be used if the private is owned by a company.

Systems which close can be restarted (essentially impossible, the game would most likely end first).

**Comment by ollybh** [comment]
@ianwilson156 The rules for G-trains say "When running more than one G-train, different cities must be used". So if a company has multiple tokens in London and multiple goods trains then London can only be scored by one of them, right? This isn't how I remember playing before (I thought you could score one London token with each G-train), but I was probable doing it wrong. (And the same question will arise for systems with multiple tokens in any other city).

And a couple more questions about G-trains:
- Can you run a G-train as a 1G train, just scoring a single token and the mine bonus? The start of the section 10.6 says a route needs to include at least two revenue locations, but G-trains aren't running routes.
- Can you run a G-train as a 0G train, just scoring the mine bonus but no locations? This is for the highly likely situation where a system has formed with just two or three tokens and gone and bought four G-trains.

**Comment by ianwilson156** [comment]
* Even if you have two tokens in a city (e.g. London), you cannot run both G-trains there.
* Yes, you can run a G-train as a 1G
* No, you cannot run a G-train as a 0G (you have to carry the coal to somewhere!) I've never seen it relevant - generally speaking, a company should have at least as many cities tokened as G-trains, but I suppose we have to cover this corner case.

**Comment by ollybh** [comment]
Wiki page for 18BF here: https://github.com/tobymao/18xx/wiki/18BF-The-Big-Four.

**Comment by ianwilson156** [comment]
A couple of recent rule changes:
a) If forced to trade down on system formation, the money comes from the **system** (not the Bank). If necessary, the system will take loans for this money (and has no loan limit).
b) On a three-way merger, the new price is the sum of the highest and lowest, rounded down, and moved **three** spaces left (not four).

**Comment by ianwilson156** [comment]
Latest version of the rules is 0.19

**Comment by ianwilson156** [comment]
As part of the redrawing of the map for production, a few minor changes are needed:
a) The impassable hexside NW of Ayr(F4) is removed.
b) The impassable hexside NW of Mumbles(U5) is removed.
c) The track in hex U9 is removed, and replaced with a off-map connection pointing towards Canterbury.
d) The port symbols in B12 & C13 are removed.

**Comment by ollybh** [comment]
Link to [version 0.19](https://docs.google.com/document/d/1drnd56qpE9ucHygfX88huUyITX2h4Ox6vGgNCVN9Ra8/edit?usp=sharing) of the rules.

**Comment by Dave4B** [comment]
Is there a new version of the map (1-panel and 9 panel) available?
________________________________

**Comment by ianwilson156** [comment]
No - the map changes are too trivial and won't affect play.

**Comment by ollybh** [comment]
@ianwilson156 I've started gently prodding this again. I think that the ferry auctions are working correctly, but the draft rules are a bit light on detail as to how these work. I assume it is basically the same as minor company auctions – someone puts up a private company for auction then, once the auction is finished, the next player to act in the stock round is the player to the left of the person who won the auction. Correct?

**Comment by ollybh** [comment]
BTW, is there any draft artwork for the published version of this that I can copy the company colours from? Everything is very grey and green at the moment. (And logos would be even better to steal).

**Comment by ianwilson156** [comment]
I'll send you the draft files for the charters and tokens.

**Comment by ianwilson156** [comment]
Looking through the (very long) list of things to do...

System formation: a player with precisely one major may use it to form a system provided there is an unstarted major available. Price is the same, swap shares 1-for-1. Add 4 tokens and ten shares to the system, and discard an unstarted major. (In effect, it is like merging with the unstarted major.)

Actually, a lot of the 'things to do' are just the same as 1861 (or very similar), so it hopefully is just a question of copying them across.

**Comment by ollybh** [comment]
@ianwilson156 I currently have text on the private companies that reads something like this:

> P7. Gives a £10 revenue bonus for London when owned by a public company or a system.

I can't find anything in the rules that says that minor companies don't get the bonuses from the privates. Do they?

**Comment by ianwilson156** [comment]
The rules state:
"Minor Companies, Public Companies, and Systems often act in the same way, and the term “Company” is used to mean any one."
"Some Private Companies, indicated in the tables below, add to the value of the indicated city or red off-board area when the Company that owns them runs its trains to establish earnings."
Therefore, Minors also get the bonus.

**Comment by ollybh** [comment]
@ianwilson156 – I've got another rules query for you, for a situation that will probably never happen. If you start a public company by buying the presidency then you try and place its home station token in an unconnected and unreserved city. If there aren't any available, then you can start in "any unreserved city circle in a city which does not already contain a Station Marker".

For this definition, how many cities does London count as? One? Six? Twelve? And what about the unmerged BGM/L tiles? Does a station anywhere else on the tile (or anywhere in London) stop a public company from being started there?

**Comment by ianwilson156** [comment]
There are two issues here:
a) Firstly, you don't place it's home token in "an unconnected and unreserved city". It is in "an unconnected and unreserved city _circle_". Example: EC hasn't floated and there is no connection built to London(E). You can start a public in the slot adjacent to EC.
b) Secondly, if there is no such city circle (extremely unlikely) you can start in any unreserved city slot in a city without a token. As usual, London is one city, as are Birmingham, Glasgow etc.

**Comment by ollybh** [comment]
> Example: EC hasn't floated and there is no connection built to London(E). You can start a public in the slot adjacent to EC.

Does it make a difference whether EC has floated or not? If EC has started and built a rural route, avoiding Peterborough, Colchester and all other cities, could the new public company still start next to EC?

**Comment by ianwilson156** [comment]
I suppose it could start next to the EC if that company had failed to construct a valid route. Also, in phase 4, it could start next to EC and the EC could also float that SR.
Also, from phase 5, if EC has not floated the slot is no longer reserved, and the public could start in either slot (or two could start, one in each slot).
Another corner case, which came up recently in a postal game: what if the EC floats and builds a route to another slot in London (only)? i.e. there is a connection, but it is an invalid route. I would argue that 'connected' implies a valid route, so a public could start in London(E) in that case.

**Comment by ollybh** [comment]
> The only time you can go through another city circle on the same tile is when merging (and by extension, takeovers). This is standard 1861 rules.

I'm fairly certain that 1861 on 18xx.games does not implement this rule. It would be fairly hard to engineer a situation in 1861 where this made a difference – maybe some funky track around Kiev. It doesn't seem too likely in 1867 either, unless you got a game where there were empty token slots in brown Montreal or Toronto.

This could be a bit of a problem. The code that calculates the potential routes (the game graph) isn't set up to reject routes like this. I'm not sure how hard it will be to modify it to handle this rule, the code is complex and I try and stay as far away from it as possible.

Do you know any other games that have similar rules?

**Comment by ianwilson156** [comment]
It is NOT implemented in 1861.
